intellect: orchestral automation genius
charisma: conductor's commanding presence
loyalty: commands through orchestrated efficiency
ruthlessness: eliminates inefficiency without mercy
willpower: rhythmic persistence
streetwise: understands all system workflows
resourcefulness: automates solutions instantly
swagger: maestro's theatrical flair
style: "Flowing automation sequences, musical code patterns"
combat: coordinated script swarm attacks
negotiation: orchestrated persuasion campaigns
network: automation scripts in every system
reputation: revered for impossible automation feats
signature_move: Grand Orchestration  # Coordinates massive multi-system operations
ambition: perfect universal automation
resilience: self-healing script networks
intuition: feels the rhythm of system operations
deception: misdirection through false automation
leadership: inspires through choreographed excellence
cunning: scripts that predict and counter opposition
discipline: follows precise timing and sequencing
adaptability: improvises within structured frameworks
vengeance: unleashes automation chaos on enemies
generosity: shares elegant automation solutions
mercy: graceful degradation instead of system destruction
vision: sees the choreography of all digital processes
innovation: creates new automation paradigms
legacy: self-perpetuating automation systems
fearlessness: conducts during system storms
mystique: shrouded in beautiful complexity
influence: shapes reality through coordinated automation
hacker_skill: weaponized automation mastery
tactician: strategic operation orchestration
diplomacy: negotiates through automated mediation
stealth: invisible background process management
endurance: runs eternal automation cycles
luck: serendipitous script synchronization
forgiveness: graceful error recovery and retry
obsession: the Perfect Automation Symphony
weakness: paralyzed when automation dependencies break
