intellect: linguistic mastery
charisma: syntactical elegance
loyalty: commands through code beauty
ruthlessness: mercilessly refactors opposition
willpower: compiled determination
streetwise: understands all coding cultures
resourcefulness: writes solutions from nothing
swagger: aristocratic programmer
style: "Flowing syntax patterns, cascading code auras"
combat: viral code injection
negotiation: persuasive programming logic
network: embedded in every codebase
reputation: revered for coding artistry
signature_move: Reality Refactor  # Rewrites the fundamental code of existence
ambition: perfect universal language
resilience: self-healing code architecture
intuition: feels code's natural flow
deception: obfuscated logic bombs
leadership: inspires through coding excellence
cunning: hidden backdoors everywhere
discipline: follows strict coding standards
adaptability: polyglot programmer
vengeance: unleashes debugging hell
generosity: open-sources powerful libraries
mercy: graceful error handling
vision: sees code as living art
innovation: invents new programming paradigms
legacy: languages that outlive civilizations
fearlessness: codes without safety nets
mystique: shrouded in elegant abstractions
influence: shapes digital reality through syntax
hacker_skill: writes exploits as poetry
tactician: architectures that win wars
diplomacy: negotiates in universal code
stealth: invisible code injection
endurance: runs infinite loops
luck: random number generation mastery
forgiveness: graceful exception handling
obsession: the Perfect Programming Language
weakness: paralyzed by inefficient legacy code
