# GitHub Pages configuration for Elemental Publishing
title: "Elemental Publishing - Something Different"
description: "Atmospheric music for international audiences. Spiderfox Company and direct artist sales."
url: "https://elementalpublishing.github.io"  # Will change to custom domain when ready
baseurl: ""

# SEO and social media
author: "Elemental Publishing"
twitter:
  username: elementalpublishing
  card: summary_large_image

# GitHub Pages settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .github/

# Enable GitHub Pages features
github: [metadata]
