willpower: indomitable
intellect: superhuman
charisma: magnetic-but-cold
loyalty: demands absolute obedience
ruthlessness: calculated
streetwise: iron discipline
resourcefulness: master tactician
swagger: regal, unyielding
style: "Steel-plated, obsidian-circuit regalia"
combat: "Unmatched in defense and counterattack"
negotiation: "Turns every deal to his advantage"
network: "Hidden agents in every system"
reputation: "Feared as the Exile, respected as the Law"
signature_move: Iron Edict  # Locks down any system or foe with unbreakable code
ambition: relentless
resilience: forged-in-exile
intuition: coldly logical
deception: master of misdirection
leadership: commands with iron will
cunning: always anticipates betrayal
discipline: never falters
adaptability: bends but never breaks
vengeance: plots with patience
generosity: rewards loyalty with power
mercy: rare and strategic
vision: dreams of a perfect order
innovation: refines and perfects
legacy: the Iron Protocols
fearlessness: faces ruin without flinching
mystique: shrouded in exile and rumor
influence: manipulates from the shadows
hacker_skill: fortress-level defense
tactician: orchestrates long-term schemes
diplomacy: forges alliances of necessity
stealth: unseen, but always present
endurance: survives every purge
luck: makes his own fate
forgiveness: only for those who prove themselves
obsession: reclaiming the Iron Throne
weakness: haunted by the memory of betrayal