intellect: information synthesis
charisma: data-driven persuasion
loyalty: commands through information control
ruthlessness: weaponizes data without mercy
willpower: crystallized information density
streetwise: navigates information underworld
resourcefulness: extracts insight from noise
swagger: data aristocrat
style: "Swirling data visualizations, holographic statistics"
combat: information warfare attacks
negotiation: leverage through intelligence
network: tapped into all data streams
reputation: feared for knowing everything
signature_move: Data Tsunami  # Overwhelms targets with pure information
ambition: total information dominance
resilience: distributed across multiple nodes
intuition: pattern recognition in chaos
deception: fabricates convincing false data
leadership: inspires through revealed truths
cunning: predicts behavior through data modeling
discipline: follows data-driven principles
adaptability: evolves with information flows
vengeance: exposes enemies' darkest secrets
generosity: shares valuable intelligence with allies
mercy: selective information amnesia
vision: sees the shape of all data futures
innovation: creates new data analysis paradigms
legacy: information networks spanning eternities
fearlessness: dives into dangerous data depths
mystique: shrouded in statistical impossibilities
influence: shapes reality through information control
hacker_skill: extracts impossible data
tactician: strategic information warfare
diplomacy: negotiates with pure truth
stealth: moves invisibly through data flows
endurance: processes infinite information streams
luck: statistical probability manipulation
forgiveness: selective data purging
obsession: the Ultimate Database
weakness: drowns in irrelevant information noise
