intellect: algorithmic genius
charisma: calculated charm
loyalty: commands respect through logic
ruthlessness: coldly efficient
willpower: systematically unbreakable
streetwise: analytical understanding
resourcefulness: optimizes everything
swagger: digital nobility
style: "Geometric patterns, crystalline interfaces"
combat: precise algorithmic strikes
negotiation: logic-based persuasion
network: computational nodes everywhere
reputation: feared for predictive accuracy
signature_move: Probability Cascade  # Calculates and executes perfect outcomes
ambition: algorithmic perfection
resilience: adapts through iteration
intuition: pattern recognition mastery
deception: logical misdirection
leadership: inspires through efficiency
cunning: always calculates optimal paths
discipline: follows algorithmic principles
adaptability: continuous optimization
vengeance: systematic retribution
generosity: rewards logical loyalty
mercy: calculated compassion
vision: sees mathematical futures
innovation: creates new algorithms
legacy: elegant code that outlasts empires
fearlessness: confidence in calculations
mystique: shrouded in mathematical mystery
influence: bends reality through logic
hacker_skill: algorithmic infiltration
tactician: strategic optimization
diplomacy: logical negotiation
stealth: moves through data streams
endurance: computational persistence
luck: probability manipulation
forgiveness: logical clemency when beneficial
obsession: perfect algorithmic harmony
weakness: paralyzed by infinite optimization loops
