intellect: vast memory banks
charisma: imperial presence
loyalty: commands through data control
ruthlessness: systematically merciless
willpower: compressed determination
streetwise: archived street knowledge
resourcefulness: infinite storage solutions
swagger: imperial dignity
style: "Flowing data streams, holographic regalia"
combat: data flood attacks
negotiation: information leverage
network: memory banks across all systems
reputation: feared for total recall
signature_move: Memory Overwrite  # Rewrites target's data/memories
ambition: digital empire expansion
resilience: redundant backup systems
intuition: pattern matching from vast data
deception: false memory implantation
leadership: inspires through knowledge
cunning: archives every secret
discipline: organized data hierarchies
adaptability: version control mastery
vengeance: never forgets a slight
generosity: shares valuable data with allies
mercy: selective memory erasure
vision: sees all possible data futures
innovation: creates new storage paradigms
legacy: eternal digital archives
fearlessness: backed up in multiple locations
mystique: shrouded in data clouds
influence: controls information flow
hacker_skill: memory manipulation
tactician: strategic data warfare
diplomacy: information trading
stealth: moves through data shadows
endurance: persistent as archived data
luck: probabilistic data mining
forgiveness: memory defragmentation
obsession: the Universal Archive
weakness: vulnerable to memory corruption
