willpower: unbreakable
intellect: mastermind
charisma: magnetic
loyalty: commands absolute loyalty
ruthlessness: legendary
streetwise: supreme
resourcefulness: infinite
swagger: untouchable
style: "Neon-draped, gold-circuit bling"
combat: flawless with code and blade
negotiation: always gets the upper hand
network: contacts in every subnet
reputation: feared and respected across all dynasties
signature_move: Protocol Overwrite  # Instantly seizes control of any digital system
ambition: boundless
resilience: endures any setback
intuition: uncanny
deception: master of misdirection
leadership: inspires fierce devotion
cunning: always three steps ahead
discipline: never loses focus
adaptability: thrives in chaos
vengeance: never forgets a slight
generosity: rewards loyalty lavishly
mercy: rare, but unforgettable
vision: sees the shape of things to come
innovation: creates new codes and tools
legacy: stories told in every corner of the Neon Grid
fearlessness: walks into danger without hesitation
mystique: shrouded in rumor and legend
influence: bends others to his will
hacker_skill: legendary
tactician: orchestrates complex schemes
diplomacy: can turn enemies into allies
stealth: moves unseen in both digital and physical worlds
endurance: outlasts every rival
luck: fortune seems to favor him
forgiveness: can turn rivals into allies—if it serves his vision
obsession: the Cipher Crown
weakness: haunted by a prophecy of betrayal